In [ ]:
#1
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
x=a.copy()
print(x)
x[2]=20
print(".................................")
print(x)


[ 1  2  3  4  5  6  7  8  9 10]
.................................
[ 1  2 20  4  5  6  7  8  9 10]


In [ ]:
#2
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=a.view()
print(x)
x[3]=20
print(".................................")
print(x)


[ 1  2  3  4  5  6  7  8  9 10]
.................................
[ 1  2  3 20  5  6  7  8  9 10]


In [ ]:
#3
a=np.array([1,2,3,4,5,6,7,8,9,10])
x=a.copy()
y=a.view()
print(x.base)
print(y.base)

None
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#4
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
view = arr[0, :]
view[0:] = 0
view[1:] = 1
print("Original array:\n", arr)
print("View:\n", view)

Original array:
 [[0 1 1]
 [4 5 6]]
View:
 [0 1 1]


In [ ]:
#5
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1[2:]
result = np.may_share_memory(arr1, arr2)
print(result)

True


In [ ]:
#6
import numpy as np
a = np.array([1, 2, 3, 4])
b = a[::2]
result = np.may_share_memory(a, b)
print(result)

True


In [ ]:
#7
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.reshape(a,(2,5))
print(b)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#8
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
b=np.shape(a)
print(a)
print("-------------------")
b=np.reshape(a,(3,3))
print(b)

[1 2 3 4 5 6 7 8 9]
-------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#9
import numpy as np
arr = np.arange(1, 13)
print("Shape of 1D array:", arr.shape)
arr_2d = arr.reshape(3, 4)
print("Shape of 2D array:", arr_2d.shape)
arr_3d = arr.reshape(2, 3, 2)
print("Shape of 3D array:", arr_3d.shape)

Shape of 1D array: (12,)
Shape of 2D array: (3, 4)
Shape of 3D array: (2, 3, 2)


In [ ]:
#10
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=np.reshape(a,(3,4))
print(b)
print("---------------------------")
c=np.reshape(b,(2,6))
print(c)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
---------------------------
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
#11
import numpy as np
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a_3d = a_2d.reshape(2, 2, 2)
print("Shape of 3D array:", a_3d.shape)
print(a_3d)
print("-------------------------")
a_2d_again = a_3d.reshape(2, 4)
print("Shape of 2D array:", a_2d_again.shape)
print(a_2d_again)

Shape of 3D array: (2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
-------------------------
Shape of 2D array: (2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#12
a=np.array([[1,2,3,4],[5,6,7,8],
            [9,10,11,12],[13,14,15,16]])
b=a.reshape(2,8)
print(b)
print("---------------------------------")
c=b.reshape(4,4)
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
---------------------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#13
a=np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
b=a.reshape(-1)
print(b)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#14
import numpy as np
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for row in a:
    for element in row:
        print(element, end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [4]:
#15
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
for idx,i in np.ndenumerate(a):
  print(idx,i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
#16
import numpy as np
a=np.array([[[1,2,3]],[[4,5,6]]])
for i in a:
  print(a)


[[[1 2 3]]

 [[4 5 6]]]
[[[1 2 3]]

 [[4 5 6]]]


In [34]:
#17
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(a):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [36]:
#18
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [40]:
#19
a=np.array([1,2,3,4,5],ndmin=6)
print(a)
print("---------------------")
for x in np.nditer(a):
  print(x)

[[[[[[1 2 3 4 5]]]]]]
---------------------
1
2
3
4
5


In [6]:
#20
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for i in np.nditer(a,["buffered"],op_dtypes=[float]):
  print(i)



1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [11]:
#21
a=np.array([1,2,3,5.4,4,5,6])
for x in np.nditer(a):
  print(x)

1.0
2.0
3.0
5.4
4.0
5.0
6.0


In [15]:
#22
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(a,flags=["buffered"],op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'


In [22]:
#23
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
for x in np.nditer(a[::2]):
    print(x)

1
3
5
7
9


In [30]:
#24
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b=a[:,1:2]
for idx,x in np.ndenumerate(b):
  print(idx, x)

(0, 0) 2
(1, 0) 7


In [33]:
#25
import numpy as np
a=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]])
print(a)
print("------------------")
for idx,x in np.ndenumerate(a[:,:,1:2]):
  print(idx,x)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]]
------------------
(0, 0, 0) 2
(0, 1, 0) 6
(0, 2, 0) 10
(0, 3, 0) 14
